CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
    SELECT 
        CASE WHEN COUNT(*) >= N AND N> 0 THEN MIN(salary) END  
    FROM (SELECT DISTINCT salary FROM Employee ORDER BY salary DESC LIMIT N) AS t
  );
END