SELECT di.ITEM_ID, di.ITEM_NAME, di.RARITY FROM ITEM_INFO ii
JOIN ITEM_TREE it ON ii.ITEM_ID = it.PARENT_ITEM_ID
JOIN ITEM_INFO di ON di.ITEM_ID = it.ITEM_ID
WHERE ii.RARITY = 'RARE'
ORDER BY di.ITEM_ID DESC
